[phases.setup]
nixPkgs = ['...', 'dotnet-sdk_8']

[phases.build]
cmds = [
    'cd backend',
    'dotnet restore',
    'dotnet publish -c Release -o /app/publish'
]

[start]
cmd = 'cd /app/publish && dotnet FlexoAPP.API.dll'
